# Generated by Django 4.1 on 2022-09-23 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='code',
        ),
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 23, 10, 12, 32, 980295)),
        ),
    ]
