# Generated by Django 4.1 on 2022-09-23 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_categorie_furniture_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='category',
            field=models.CharField(max_length=42, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 23, 10, 21, 53, 234654)),
        ),
    ]
