# Generated by Django 4.1 on 2022-09-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_furniture_upload_alter_furniture_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 23, 10, 46, 49, 936021)),
        ),
    ]
