# Generated by Django 4.1 on 2022-09-23 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_furniture_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='url_img',
        ),
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 23, 12, 1, 23, 27324)),
        ),
    ]
