# Generated by Django 4.1 on 2022-09-30 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_furniture_price_alter_furniture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 30, 12, 58, 39, 570758)),
        ),
    ]
