# Generated by Django 4.1 on 2022-09-30 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_furniture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 30, 13, 2, 28, 411670)),
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('furniture', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.furniture')),
            ],
        ),
    ]
