# Generated by Django 4.1 on 2022-10-02 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_furniture_caracteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 15, 15, 14, 113908)),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='title',
            field=models.CharField(max_length=35, verbose_name='titre (30 caractère max'),
        ),
    ]
