# Generated by Django 4.1 on 2022-10-02 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_furniture_date_alter_furniture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 15, 53, 39, 285942)),
        ),
    ]
