# Generated by Django 4.1 on 2022-10-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_furniture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
