# Generated by Django 4.0 on 2023-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_furniture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name="texte alternatif à l'image"),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='caracteristic',
            field=models.CharField(max_length=255, verbose_name='caractéristiques : massif plaque boulle siege // marqueterie sculpture boite_et_coffret jeux bijoux'),
        ),
    ]
