# Generated by Django 4.0 on 2023-01-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_furniture_alt_alter_furniture_caracteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='alt',
            field=models.CharField(default='None', max_length=255, verbose_name="texte alternatif à l'image"),
        ),
    ]
